In [1]:
import pandas as pd

In [2]:
sanbul = pd.read_excel('C:\project22\sanbul.xls'
                       , sheet_name = "Sheet1")

In [3]:
# 열 이름이 되야할 데이터 추출
index_fix = sanbul.loc[1]

# 열이름 변경
sanbul.columns = index_fix

# 필요없는 행 제거
sanbul = sanbul.drop([0, 1])

# 년 월 일 합치기?
# 날짜 데이터와 형태 같게 만들기 yyyy-mm-dd
sanbul['tm'] = sanbul['발생일시_년'] + '-' + sanbul['발생일시_월'] + '-' + sanbul['발생일시_일']


# 발생장소_시도 = 강원, 경북, 울진만 추출

condition = (sanbul.발생장소_시도 == '강원') | (sanbul.발생장소_시도 == '경북') | (sanbul.발생장소_시도 == '울산')
sanbul_region = sanbul[condition]

In [4]:
# 필요 한 열 추출
sanbul_data = sanbul_region[['tm', '발생일시_월','발생일시_시간','발생장소_시도', '발생장소_시군구', '발생원인_구분', '피해면적_합계']]
# 결츨치 확인 = 없음
sanbul_data.isnull().sum()

1
tm          0
발생일시_월      0
발생일시_시간     0
발생장소_시도     0
발생장소_시군구    0
발생원인_구분     0
피해면적_합계     0
dtype: int64

In [12]:
sanbul.groupby('발생일시_요일').count()

1,발생일시_년,발생일시_월,발생일시_일,발생일시_시간,진화종료시간_년,진화종료시간_월,진화종료시간_일,진화종료시간_시간,발생장소_관서,발생장소_시도,발생장소_시군구,발생장소_읍면,발생장소_동리,발생원인_구분,발생원인_세부원인,발생원인_기타,피해면적_합계,tm
발생일시_요일,,,,,,,,,,,,,,,,,,
공,131,131,131,131,131,131,131,131,131,131,131,122,121,131,131,46,131,131
금,610,610,610,610,610,610,610,610,610,610,610,592,530,610,607,221,610,610
목,621,621,621,621,621,621,621,621,621,621,621,599,539,621,619,194,621,621
수,634,634,634,634,634,634,634,634,634,634,634,611,543,634,634,184,634,634
월,613,613,613,613,613,613,613,613,613,613,613,587,509,613,611,189,613,613
일,792,792,792,792,792,792,792,792,792,792,792,765,667,792,789,227,792,792
토,754,754,754,754,754,754,754,754,754,754,754,733,630,754,753,241,754,754
화,654,654,654,654,654,654,654,654,654,654,654,629,560,654,653,183,654,654

In [5]:
sanbul.groupby('발생일시_월').count()
# 추출할 열 2 ,3, 4, 5, 6

1,발생일시_년,발생일시_일,발생일시_시간,발생일시_요일,진화종료시간_년,진화종료시간_월,진화종료시간_일,진화종료시간_시간,발생장소_관서,발생장소_시도,발생장소_시군구,발생장소_읍면,발생장소_동리,발생원인_구분,발생원인_세부원인,발생원인_기타,피해면적_합계,tm
발생일시_월,,,,,,,,,,,,,,,,,,
01,343,343,343,343,343,343,343,343,343,343,343,331,286,343,342,87,343,343
02,566,566,566,566,566,566,566,566,566,566,566,547,469,566,565,168,566,566
03,1236,1236,1236,1236,1236,1236,1236,1236,1236,1236,1236,1201,1031,1236,1230,229,1236,1236
04,1055,1055,1055,1055,1055,1055,1055,1055,1055,1055,1055,1017,913,1055,1053,320,1055,1055
05,488,488,488,488,488,488,488,488,488,488,488,477,421,488,487,121,488,488
06,357,357,357,357,357,357,357,357,357,357,357,345,303,357,357,139,357,357
07,56,56,56,56,56,56,56,56,56,56,56,54,48,56,56,19,56,56
08,89,89,89,89,89,89,89,89,89,89,89,88,80,89,89,49,89,89
09,58,58,58,58,58,58,58,58,58,58,58,58,52,58,58,13,58,58
10,140,140,140,140,140,140,140,140,140,140,140,132,122,140,140,64,140,140
11,202,202,202,202,202,202,202,202,202,202,202,188,178,202,201,139,202,202
12,219,219,219,219,219,219,219,219,219,219,219,200,196,219,219,137,219,219

In [6]:
condition = (sanbul.발생장소_시도 == '강원') | (sanbul.발생장소_시도 == '경북') | (sanbul.발생장소_시도 == '울산')
sanbul_region = sanbul[condition]

In [7]:
month = (sanbul.발생일시_월 == '02') | (sanbul.발생일시_월 == '03') | (sanbul.발생일시_월 == '04')| (sanbul.발생일시_월 == '05')| (sanbul.발생일시_월 == '06')
sanbul_mon = sanbul_region[month]

C:\Users\user\AppData\Local\Temp\ipykernel_17248\519296382.py:2: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  sanbul_mon = sanbul_region[month]

In [8]:
sanbul_region

1,발생일시_년,발생일시_월,발생일시_일,발생일시_시간,발생일시_요일,진화종료시간_년,진화종료시간_월,진화종료시간_일,진화종료시간_시간,발생장소_관서,발생장소_시도,발생장소_시군구,발생장소_읍면,발생장소_동리,발생원인_구분,발생원인_세부원인,발생원인_기타,피해면적_합계,tm
2,2021,12,30,14:57,목,2021,12,30,17:30,경북,경북,봉화,명호,양곡,건,주택화재비화,NaN,0.5,2021-12-30
8,2021,12,29,02:42,수,2021,12,29,15:45,북부,강원,춘천,사북,가일,건,주택화재비화,NaN,4,2021-12-29
11,2021,12,24,15:00,금,2021,12,24,16:23,경북,경북,고령,상림,합가,입,기타(직접입력),입산자실화,0.04,2021-12-24
12,2021,12,24,14:54,금,2021,12,24,16:20,경북,경북,경주,강동,호명,입,기타(직접입력),입산자실화추정,1,2021-12-24
13,2021,12,23,19:14,목,2021,12,23,20:00,울산,울산,울주,웅촌,곡천,입,기타(직접입력),입산자실화,0.01,2021-12-23
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4796,2012,02,28,14:40,화,2012,02,28,14:40,강원,강원,양구,동면,팔랑,기,성묘객실화,NaN,0.06,2012-02-28
4803,2012,02,16,14:05,목,2012,02,16,15:15,강원,강원,원주,소초,둔둔,건,주택화재비화,NaN,0.1,2012-02-16
4804,2012,02,05,16:28,일,2012,02,05,16:49,강원,강원,고성,거진,거진,입,입산자실화,NaN,0.2,2012-02-05
4807,2012,01,11,15:15,수,2012,01,11,16:50,북부,강원,홍천,홍천,하오안,입,등산객실화,NaN,0.03,2012-01-11
4809,2012,01,09,12:15,월,2012,01,09,13:40,경북,경북,영덕,지품,오천,건,보일러과열,NaN,0.1,2012-01-09

In [9]:
rank_df = sanbul_region

rank_df['피해면적_합계'] = rank_df['피해면적_합계'].astype(float)

rank_df['rank'] = rank_df['피해면적_합계'].rank(ascending = False)

# rank_df[(rank_df['rank'] < 20)]
rank_df = rank_df.sort_values(by = 'rank', ignore_index = True)

rank_df

C:\Users\user\AppData\Local\Temp\ipykernel_17248\382703824.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  rank_df['피해면적_합계'] = rank_df['피해면적_합계'].astype(float)
C:\Users\user\AppData\Local\Temp\ipykernel_17248\382703824.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  rank_df['rank'] = rank_df['피해면적_합계'].rank(ascending = False)

1,발생일시_년,발생일시_월,발생일시_일,발생일시_시간,발생일시_요일,진화종료시간_년,진화종료시간_월,진화종료시간_일,진화종료시간_시간,발생장소_관서,발생장소_시도,발생장소_시군구,발생장소_읍면,발생장소_동리,발생원인_구분,발생원인_세부원인,발생원인_기타,피해면적_합계,tm,rank
0,2020,04,24,15:39,금,2020,04,27,18:00,경북,경북,안동,풍천,인금,입,기타(직접입력),입산자실화 추정,1944.00,2020-04-24,1.0
1,2019,04,04,19:17,목,2019,04,05,18:00,강원,강원,고성,토성,원암,기,특고압 전선 아크 불티,NaN,1266.62,2019-04-04,2.0
2,2019,04,04,23:46,목,2019,04,05,21:30,강원,강원,강릉,옥계,남양,기,신당 전기초 합선,NaN,1260.15,2019-04-04,3.0
3,2017,05,06,11:42,토,2017,05,09,11:20,강원,강원,삼척,도계,점,입,기타(직접입력),입산자 실화,765.12,2017-05-06,4.0
4,2020,03,19,13:51,목,2020,03,20,18:00,울산,울산,울주,웅촌,대복,입,기타(직접입력),입산자실화,519.00,2020-03-19,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1624,2019,05,17,14:01,금,2019,05,17,15:00,울산,울산,중,성안,NaN,입,입산자 실화,NaN,0.01,2019-05-17,1501.0
1625,2016,11,29,04:35,화,2016,11,29,05:30,강원,강원,강릉,주문진,장덕,기,기타(직접입력),차량화재로 인한 산화,0.01,2016-11-29,1501.0
1626,2020,12,06,13:00,일,2020,12,06,14:00,울산,울산,남,NaN,부곡,입,기타(직접입력),입산자실화,0.01,2020-12-06,1501.0
1627,2014,02,03,15:02,월,2014,02,03,15:20,경북,경북,포항 북,홍해,학천,입,입산자 실화 추정,NaN,0.01,2014-02-03,1501.0
1628,2013,05,14,20:04,화,2013,05,14,22:00,경북,경북,영덕,축산,기암,입,입산자실화,NaN,0.01,2013-05-14,1501.0

In [10]:
# 피해면적 비율 계산하기

# 전체 피해면적 합산
total_area = rank_df['피해면적_합계'].sum()

# 피해면적/total_area 비율 계산 100%로 계산
rank_df['radio'] = rank_df['피해면적_합계']/total_area * 100

# 피해면적 누계 계산 # 누계합 함수 cumsum
rank_df['cumulative'] = rank_df['피해면적_합계'].cumsum()

rank_df['cumulative'] = rank_df['radio'].cumsum()

In [17]:
rank_df.head()

1,발생일시_년,발생일시_월,발생일시_일,발생일시_시간,발생일시_요일,진화종료시간_년,진화종료시간_월,진화종료시간_일,진화종료시간_시간,발생장소_관서,...,발생장소_읍면,발생장소_동리,발생원인_구분,발생원인_세부원인,발생원인_기타,피해면적_합계,tm,rank,radio,cumulative
0,2020,04,24,15:39,금,2020,04,27,18:00,경북,...,풍천,인금,입,기타(직접입력),입산자실화 추정,1944.00,2020-04-24,1.0,20.166979,20.166979
1,2019,04,04,19:17,목,2019,04,05,18:00,강원,...,토성,원암,기,특고압 전선 아크 불티,NaN,1266.62,2019-04-04,2.0,13.139866,33.306845
2,2019,04,04,23:46,목,2019,04,05,21:30,강원,...,옥계,남양,기,신당 전기초 합선,NaN,1260.15,2019-04-04,3.0,13.072746,46.379592
3,2017,05,06,11:42,토,2017,05,09,11:20,강원,...,도계,점,입,기타(직접입력),입산자 실화,765.12,2017-05-06,4.0,7.937325,54.316916
4,2020,03,19,13:51,목,2020,03,20,18:00,울산,...,웅촌,대복,입,기타(직접입력),입산자실화,519.00,2020-03-19,5.0,5.384086,59.701002

In [19]:
sanbul_mon['month_count'] = sanbul['발생일시_월'] + sanbul['발생장소_시도']
sanbul_mon.groupby('month_count').count()

C:\Users\user\AppData\Local\Temp\ipykernel_17248\2911647688.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sanbul_mon['month_count'] = sanbul['발생일시_월'] + sanbul['발생장소_시도']

1,발생일시_년,발생일시_월,발생일시_일,발생일시_시간,발생일시_요일,진화종료시간_년,진화종료시간_월,진화종료시간_일,진화종료시간_시간,발생장소_관서,발생장소_시도,발생장소_시군구,발생장소_읍면,발생장소_동리,발생원인_구분,발생원인_세부원인,발생원인_기타,피해면적_합계,tm
month_count,,,,,,,,,,,,,,,,,,,
02강원,55,55,55,55,55,55,55,55,55,55,55,55,54,53,55,55,21,55,55
02경북,104,104,104,104,104,104,104,104,104,104,104,104,103,98,104,104,33,104,104
02울산,25,25,25,25,25,25,25,25,25,25,25,25,24,19,25,25,7,25,25
03강원,142,142,142,142,142,142,142,142,142,142,142,142,141,130,142,142,31,142,142
03경북,178,178,178,178,178,178,178,178,178,178,178,178,176,164,178,176,27,178,178
03울산,25,25,25,25,25,25,25,25,25,25,25,25,22,20,25,25,6,25,25
04강원,150,150,150,150,150,150,150,150,150,150,150,150,150,145,150,150,51,150,150
04경북,147,147,147,147,147,147,147,147,147,147,147,147,145,145,147,146,44,147,147
04울산,13,13,13,13,13,13,13,13,13,13,13,13,11,10,13,13,7,13,13
05강원,143,143,143,143,143,143,143,143,143,143,143,143,142,140,143,143,42,143,143
05경북,87,87,87,87,87,87,87,87,87,87,87,87,87,83,87,87,25,87,87
05울산,9,9,9,9,9,9,9,9,9,9,9,9,9,3,9,9,1,9,9
06강원,68,68,68,68,68,68,68,68,68,68,68,68,68,67,68,68,23,68,68
06경북,72,72,72,72,72,72,72,72,72,72,72,72,72,69,72,72,32,72,72
06울산,3,3,3,3,3,3,3,3,3,3,3,3,2,2,3,3,1,3,3

In [16]:
rank_df.to_csv('./month_place_sanbul.csv', encoding = 'euc_kr')