In [1]:
import pandas as pd
import numpy as np

# 히트맵 그려보기
# %amtplotlib inline
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
sanbul_24 = pd.read_excel('C:\project22\sanbul.xls'
                       , sheet_name = "Sheet1")

sanbul_19 = pd.read_csv('C:\project22\python\sanbul_90_14.csv')

In [3]:
# 열 이름이 되야할 데이터 추출
index_fix = sanbul_24.loc[1]

# 열이름 변경
sanbul_24.columns = index_fix

# 필요없는 행 제거
sanbul_24 = sanbul_24.drop([0, 1])

sanbul_24['tm'] = sanbul_24['발생일시_년'] + '-' + sanbul_24['발생일시_월'] + '-' + sanbul_24['발생일시_일']

In [4]:
sanbul = pd.concat([sanbul_19, sanbul_24],  axis = 0)
# sanbul = pd.merge(sanbul_19, sanbul_24, )

In [5]:
sanbul_19.columns
sanbul_24.columns

Index(['발생일시_년', '발생일시_월', '발생일시_일', '발생일시_시간', '발생일시_요일', '진화종료시간_년',
       '진화종료시간_월', '진화종료시간_일', '진화종료시간_시간', '발생장소_관서', '발생장소_시도', '발생장소_시군구',
       '발생장소_읍면', '발생장소_동리', '발생원인_구분', '발생원인_세부원인', '발생원인_기타', '피해면적_합계',
       'tm'],
      dtype='object', name=1)

In [6]:
sanbul.columns

Index(['Unnamed: 0', '평균풍향', '최대풍향', '피해면적', '피해액', '진화종료시간_시간', '진화일시(년월일시분)',
       '실효습도', '최소습도', '상대습도', '발생원인_세부원인', '발생장소_시도', '발생일시', '발생장소_읍면',
       '발생장소_관서', '발생장소(지번)', '발생장소_동리', '발생장소_시군구', '발생일시_요일', '소유구분',
       '최종강우량', '강우경과일수', '산불위험지수(평균)', '산불위험지수(최대)', '평균기온', '평균풍속', '최대풍속',
       '발생일시_월', 'tm', '발생일시_년', '발생일시_일', '발생일시_시간', '진화종료시간_년', '진화종료시간_월',
       '진화종료시간_일', '발생원인_구분', '발생원인_기타', '피해면적_합계'],
      dtype='object')

In [7]:
sanbul.dropna( subset = ['Unnamed: 0', '평균풍향', '최대풍향', '진화종료시간_시간', '발생장소(지번)', '발생장소_동리',  '최종강우량', '강우경과일수', '산불위험지수(평균)', '산불위험지수(최대)', '평균기온', '평균풍속', '최대풍속',  '발생일시_년', '발생일시_일', '발생일시_시간', '진화종료시간_년', '진화종료시간_월',
       '진화종료시간_일'],inplace = True, axis = 1)
sanbul.columns

KeyError: ['Unnamed: 0', '평균풍향', '최대풍향', '진화종료시간_시간', '발생장소(지번)', '발생장소_동리', '최종강우량', '강우경과일수', '산불위험지수(평균)', '산불위험지수(최대)', '평균기온', '평균풍속', '최대풍속', '발생일시_년', '발생일시_일', '발생일시_시간', '진화종료시간_년', '진화종료시간_월', '진화종료시간_일']

,Unnamed: 0,평균풍향,최대풍향,피해면적,피해액,진화종료시간_시간,진화일시(년월일시분),실효습도,최소습도,상대습도,...,tm,발생일시_년,발생일시_일,발생일시_시간,진화종료시간_년,진화종료시간_월,진화종료시간_일,발생원인_구분,발생원인_기타,피해면적_합계
0,0.0,SE,S,0.19,0.0,300.0,2.014062e+11,0.0,0.0,57.0,...,2014-06-19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2.0,NW,SSW,0.05,0.0,310.0,2.014062e+11,0.0,0.0,57.0,...,2014-06-15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,4.0,NNE,SSE,0.01,0.0,242.0,2.014061e+11,0.0,0.0,40.0,...,2014-06-10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,6.0,N,S,0.10,0.0,625.0,2.014060e+11,0.0,0.0,75.0,...,2014-06-02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,8.0,SSW,N,0.10,0.0,405.0,2.014060e+11,0.0,0.0,51.0,...,2014-06-02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4806,NaN,NaN,NaN,NaN,NaN,09:40,NaN,NaN,NaN,NaN,...,2012-01-14,2012,14,22:15,2012,01,15,기,NaN,2
4807,NaN,NaN,NaN,NaN,NaN,16:50,NaN,NaN,NaN,NaN,...,2012-01-11,2012,11,15:15,2012,01,11,입,NaN,0.03
4808,NaN,NaN,NaN,NaN,NaN,16:15,NaN,NaN,NaN,NaN,...,2012-01-11,2012,11,14:30,2012,01,11,입,NaN,0.1
4809,NaN,NaN,NaN,NaN,NaN,13:40,NaN,NaN,NaN,NaN,...,2012-01-09,2012,09,12:15,2012,01,09,건,NaN,0.1
4810,NaN,NaN,NaN,NaN,NaN,13:04,NaN,NaN,NaN,NaN,...,2012-01-05,2012,05,11:39,2012,01,05,입,NaN,0.1

In [ ]:
sanbul.groupby('발생장소_시도').count()

,Unnamed: 0,평균풍향,최대풍향,피해면적,피해액,진화종료시간_시간,진화일시(년월일시분),실효습도,최소습도,상대습도,...,tm,발생일시_년,발생일시_일,발생일시_시간,진화종료시간_년,진화종료시간_월,진화종료시간_일,발생원인_구분,발생원인_기타,피해면적_합계
발생장소_시도,,,,,,,,,,,,,,,,,,,,,
강원,1184,1184,205,1184,1184,1904,1184,1184,1184,1184,...,1904,720,720,720,720,720,720,720,242,720
경기,0,0,0,0,0,1017,0,0,0,0,...,1017,1017,1017,1017,1017,1017,1017,1017,285,1017
경남,0,0,0,0,0,399,0,0,0,0,...,399,399,399,399,399,399,399,399,147,399
경북,1536,1536,241,1536,1536,2338,1536,1536,1536,1536,...,2338,802,802,802,802,802,802,802,267,802
광주,0,0,0,0,0,32,0,0,0,0,...,32,32,32,32,32,32,32,32,4,32
대구,0,0,0,0,0,81,0,0,0,0,...,81,81,81,81,81,81,81,81,40,81
대전,0,0,0,0,0,74,0,0,0,0,...,74,74,74,74,74,74,74,74,16,74
부산,0,0,0,0,0,122,0,0,0,0,...,122,122,122,122,122,122,122,122,42,122
서울,0,0,0,0,0,115,0,0,0,0,...,115,115,115,115,115,115,115,115,45,115
세종,0,0,0,0,0,32,0,0,0,0,...,32,32,32,32,32,32,32,32,11,32
울산,0,0,0,0,0,107,0,0,0,0,...,107,107,107,107,107,107,107,107,40,107
인천,0,0,0,0,0,182,0,0,0,0,...,182,182,182,182,182,182,182,182,54,182
전남,0,0,0,0,0,396,0,0,0,0,...,396,396,396,396,396,396,396,396,83,396
전북,0,0,0,0,0,229,0,0,0,0,...,229,229,229,229,229,229,229,229,60,229
제주,0,0,0,0,0,5,0,0,0,0,...,5,5,5,5,5,5,5,5,2,5
충남,0,0,0,0,0,272,0,0,0,0,...,272,272,272,272,272,272,272,272,97,272
충북,0,0,0,0,0,224,0,0,0,0,...,224,224,224,224,224,224,224,224,50,224