In [1]:
import numpy as np
import pandas as pd

In [2]:
# hs / bec 파일 불러오기, excel 파일의 두번째 sheet
hs_bec = pd.read_excel('C:\project2\BEC5Correlations\HS2012-17-BEC5 -- 08 Nov 2018.xlsx'
                       , sheet_name = "HS17BEC5")

# hs4, hs6, bec, bec processing, bec specitication 목록만 별도로 추출
hs_bec = hs_bec[['HS4','HS6','BEC5Code1', 'BEC5Processing', 'BEC5Specification']]

# hs code -> code 이름변경
hs_bec.rename(columns={'HS4':'HS4', 'HS6':'HS', 'BEC5Code1':'BEC', }, inplace=True)

In [3]:
hs4_bec = hs_bec[['HS4','BEC']]

# hs4, bec코드 정리
hs4_bec['HS4'] = hs4_bec['HS4'].astype('int')


hs4_bec.dropna(axis=0, inplace= True)
# hs4_count = hs4_bec['HS4'].value_counts()
# hs4_count = pd.DataFrame(hs4_count)

# hs4_count.reset_index(inplace=True)
# hs4_count.columns = ['HS4', 'HS4_COUNT']
# hs4_bec.groupby('HS4').count()

hs4_bec['HS4'] = hs4_bec['HS4'].astype('int')
hs4_bec['BEC'] = hs4_bec['BEC'].astype('float')

C:\Users\user\AppData\Local\Temp\ipykernel_8936\1669214109.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hs4_bec['HS4'] = hs4_bec['HS4'].astype('int')
C:\Users\user\AppData\Local\Temp\ipykernel_8936\1669214109.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hs4_bec.dropna(axis=0, inplace= True)
C:\Users\user\AppData\Local\Temp\ipykernel_8936\1669214109.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hs4_bec['HS4'] = hs4_bec['HS4'].astype('int')
C:\Users\user\AppData\Local\Temp\ipykernel_8936\1669214109.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hs4_bec['BEC'] = hs4_bec['BEC'].astype('float')

In [4]:
hs4 = hs4_bec['HS4']

hs4.drop_duplicates(inplace=True)

hs4 = hs4.to_frame()

hs4.reset_index(inplace=True)
hs4.count()

C:\Users\user\AppData\Local\Temp\ipykernel_8936\909227547.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hs4.drop_duplicates(inplace=True)

index    1222
HS4      1222
dtype: int64

In [5]:
# hs4에 대하여 bec 코드가 없는 행
# bec 값에 0

hs4_bec.loc[3513,'HS4'] = 0
hs4_bec.loc[3542,'HS4'] = 0

C:\Users\user\AppData\Local\Temp\ipykernel_8936\1599587323.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hs4_bec.loc[3513,'HS4'] = 0

In [6]:
#hs4와 bec 사전 만들기

from collections import defaultdict
hs4_dict = defaultdict(list)
    
hs4_bec.loc[0, 'HS4']
for i in range(len(hs4)) :  # hs4코드만 있는 데이터 프레임 #1222개
    hs4Temp = hs4.loc[i, 'HS4']
    for j in range(len(hs4_bec)):   #hs4와 bec 코드가 함께 있음 # 5387개
        hsbecTemp = hs4_bec.loc[j, 'HS4']
        if hs4Temp == hsbecTemp and hs4_bec.loc[j, 'BEC'] not in hs4_dict[hs4Temp]:
            hs4_dict[hs4Temp].append(hs4_bec.loc[j, 'BEC'])
        pass

In [7]:
# import pickle

# with open('hs4_dict.pickle','wb') as fw:
#     pickle.dump(hs4_dict, fw)

# with open('hs4_dict.pickle', 'rb') as fr:
#     hs4_dict = pickle.load(fr)

In [8]:
# india exported 파일 불러오기
india_exported_list = pd.read_table('C:\project2\Trade_map_List_of_products_exported_and_imported\Trade_Map_-_List_of_products_exported_by_India.txt', sep = '\t')

# code -> hs로 컬럼 이름 변경
india_exported_list.rename(columns={'Code':'HS'}, inplace=True)
india_exported_list.head()

,HS,Product label,Exported value in 2012,Exported value in 2013,Exported value in 2014,Exported value in 2015,Exported value in 2016,Exported value in 2017,Exported value in 2018,Exported value in 2019,Exported value in 2020,Exported value in 2021,Unnamed: 12
0,TOTAL,All products,289564769,336611389,317544642,263889005,260963959,295862157,323997680,323250726,275488745,394813673,NaN
1,271019,"Medium oils and preparations, of petroleum or ...",30189091,46921811,40682152,17629287,16081655,22227429,32327270,29790424,17626804,34867787,NaN
2,710239,"Diamonds, worked, but not mounted or set (excl...",20819464,27084559,22475223,20556917,22437928,22882992,24254392,20575455,14655837,23844452,NaN
3,271012,"Light oils and preparations, of petroleum or b...",0,19765201,19742787,11962340,10664422,12477483,14810618,12646438,8453439,19167099,NaN
4,300490,Medicaments consisting of mixed or unmixed pro...,6631679,8375464,8288881,9327226,9796992,9658816,10782950,12390505,14059367,14718722,NaN

In [9]:
#   1) code 열에 total -> 0으로 변경
# korea_exported_list.loc[0, 'HS'] = 000000
# 제거
india_exported_list = india_exported_list.drop([india_exported_list.index[0]])

#   2) japan 데이터 프레임에 hs 코드 데이터 타입 형변환
india_exported_list['HS'] = pd.to_numeric(india_exported_list['HS'])

#   2) merge를 사용해 hs코드 기준으로 데이터 프레임 병합
india_exported_list = pd.merge(india_exported_list, hs_bec, how='left', on='HS')

#   2-1) hs 코드 자리수 맞춰주기 -> 5자리인경우 앞에 0붙여주기
india_exported_list['HS'] = india_exported_list['HS'].astype('str')
#       HS코드 6자리로 맞춰주기, 없는경우 left에 0으로 붙여줌
# india_exported_list['HS'].str.pad(width=6, side='left', fillchar='0')
india_exported_list['HS'] = india_exported_list['HS'].str.zfill(width=6)

#   2-2 hs코드 잘라서 hs4에 넣어주기
india_exported_list['HS4'] = india_exported_list['HS'].str.slice(0, 4)


india_exported_list.head()

,HS,Product label,Exported value in 2012,Exported value in 2013,Exported value in 2014,Exported value in 2015,Exported value in 2016,Exported value in 2017,Exported value in 2018,Exported value in 2019,Exported value in 2020,Exported value in 2021,Unnamed: 12,HS4,BEC,BEC5Processing,BEC5Specification
0,271019,"Medium oils and preparations, of petroleum or ...",30189091,46921811,40682152,17629287,16081655,22227429,32327270,29790424,17626804,34867787,NaN,2710,213101.0,PRIMARY,NaN
1,710239,"Diamonds, worked, but not mounted or set (excl...",20819464,27084559,22475223,20556917,22437928,22882992,24254392,20575455,14655837,23844452,NaN,7102,411210.0,PROCESSED,GENERIC
2,271012,"Light oils and preparations, of petroleum or b...",0,19765201,19742787,11962340,10664422,12477483,14810618,12646438,8453439,19167099,NaN,2710,213101.0,PRIMARY,NaN
3,300490,Medicaments consisting of mixed or unmixed pro...,6631679,8375464,8288881,9327226,9796992,9658816,10782950,12390505,14059367,14718722,NaN,3004,711220.0,PROCESSED,SPECIFIC
4,711319,"Articles of jewellery and parts thereof, of pr...",17276723,9572682,11222490,7388131,9204800,8371671,11609406,12366518,5678174,8430817,NaN,7113,413202.0,PROCESSED,NaN

In [10]:
no_exported_id = india_exported_list[(india_exported_list['Exported value in 2017'] == 0)
                    & (india_exported_list['Exported value in 2018'] == 0)
                    & (india_exported_list['Exported value in 2019'] == 0)
                    & (india_exported_list['Exported value in 2020'] == 0)
                    & (india_exported_list['Exported value in 2021'] == 0)].index

# 거래품목 없는 인덱스 제거
india_exported_list = india_exported_list.drop(no_exported_id)
india_exported_list.isnull().sum()

HS                           0
Product label                0
Exported value in 2012       0
Exported value in 2013       0
Exported value in 2014       0
Exported value in 2015       0
Exported value in 2016       0
Exported value in 2017       0
Exported value in 2018       0
Exported value in 2019       0
Exported value in 2020       0
Exported value in 2021       0
Unnamed: 12               5239
HS4                          0
BEC                         66
BEC5Processing             762
BEC5Specification         1713
dtype: int64

In [11]:
add_BEC = india_exported_list[india_exported_list['BEC'].isnull()]
# NaN값을 채워지기 위해 hs타입 형변환??
# add_BEC['HS'] = add_BEC['HS'].astype('float')
add_BEC

# 행을 늘려주기 위한 변수
hs4_count = hs4_bec.groupby('HS4').count()

# BEC 코드를 새로 부여하기 위해 기존 BEC 행 제거
add_BEC.drop(['BEC'], axis=1, inplace=True)

add_BEC.head()

C:\Users\user\AppData\Local\Temp\ipykernel_8936\3427973275.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  add_BEC.drop(['BEC'], axis=1, inplace=True)

,HS,Product label,Exported value in 2012,Exported value in 2013,Exported value in 2014,Exported value in 2015,Exported value in 2016,Exported value in 2017,Exported value in 2018,Exported value in 2019,Exported value in 2020,Exported value in 2021,Unnamed: 12,HS4,BEC5Processing,BEC5Specification
603,999999,Commodities not elsewhere specified,2527225,5013624,959798,2293003,820957,277469,178658,212037,99582,88618,NaN,9999,NaN,NaN
4992,291470,"Halogenated, sulphonated, nitrated or nitrosat...",64724,77189,79706,86934,74487,9610,0,0,0,0,NaN,2914,NaN,NaN
5007,300210,Antisera and other blood fractions and immunol...,40082,57442,47849,45064,86696,17211,0,0,0,0,NaN,3002,NaN,NaN
5008,300440,Medicaments containing alkaloids or derivative...,79025,44566,41632,49552,45286,2503,0,0,0,0,NaN,3004,NaN,NaN
5028,441232,Plywood consisting solely of sheets of wood <=...,944,193,1239,1140,602,7,0,0,0,0,NaN,4412,NaN,NaN

In [12]:
## hs4 와 bec 개수 
hs4_bec_count = hs4_bec
# hs4와 bec 겹치는 행제거
hs4_bec_count.drop_duplicates(inplace=True)

# hs4별 bec 개수 데이터 프레임 : hs4_count 
hs4_count = hs4_bec_count.groupby('HS4').count()

In [13]:
hs4_count

        BEC
HS4
0.0       0
101.0     2
102.0     2
103.0     2
104.0     1
...     ...
9702.0    1
9703.0    1
9704.0    1
9705.0    1
9706.0    1

[1223 rows x 1 columns]

In [14]:
hs4_count.loc[101]

BEC    2
Name: 101.0, dtype: int64

In [18]:
add_BEC_index = (add_BEC.index).to_list()
hs4_count_index = (hs4_count.index).to_list()

### 행 늘리기 - how
# 1. 늘려야하는 행들 확인
# 2. n개로 행 늘려주기
for i in add_BEC_index:
    com_key = int(add_BEC.loc[i, 'HS4'])
    for j in hs4_count_index:
        count = int(hs4_count.loc[j])       # count개수만큼 행 추가
        hs4Temp = int(j)
        # print(hs4Temp)
        # print(count, hs4Temp, com_key)
        if (count > 1) & (com_key == hs4Temp):  # 추가해야할 행이 2개이상이고, com_key와 hs4Tmep이 같을 경우
            for m in range(count):  # count 개수만큼 행 추가
                add_BEC = pd.concat([add_BEC, add_BEC.loc[[i]]], ignore_index = True)

In [19]:
add_BEC

,HS,Product label,Exported value in 2012,Exported value in 2013,Exported value in 2014,Exported value in 2015,Exported value in 2016,Exported value in 2017,Exported value in 2018,Exported value in 2019,Exported value in 2020,Exported value in 2021,Unnamed: 12,HS4,BEC5Processing,BEC5Specification
0,999999,Commodities not elsewhere specified,2527225,5013624,959798,2293003,820957,277469,178658,212037,99582,88618,NaN,9999,NaN,NaN
1,291470,"Halogenated, sulphonated, nitrated or nitrosat...",64724,77189,79706,86934,74487,9610,0,0,0,0,NaN,2914,NaN,NaN
2,300210,Antisera and other blood fractions and immunol...,40082,57442,47849,45064,86696,17211,0,0,0,0,NaN,3002,NaN,NaN
3,300440,Medicaments containing alkaloids or derivative...,79025,44566,41632,49552,45286,2503,0,0,0,0,NaN,3004,NaN,NaN
4,441232,Plywood consisting solely of sheets of wood <=...,944,193,1239,1140,602,7,0,0,0,0,NaN,4412,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96,852851,Monitors of a kind solely or principally used ...,4289,2959,1779,1089,2717,618,0,0,0,0,NaN,8528,NaN,NaN
97,852851,Monitors of a kind solely or principally used ...,4289,2959,1779,1089,2717,618,0,0,0,0,NaN,8528,NaN,NaN
98,940151,Seats of bamboo or rattan,264,485,295,29,89,4,0,0,0,0,NaN,9401,NaN,NaN
99,940151,Seats of bamboo or rattan,264,485,295,29,89,4,0,0,0,0,NaN,9401,NaN,NaN
100,940151,Seats of bamboo or rattan,264,485,295,29,89,4,0,0,0,0,NaN,9401,NaN,NaN

In [44]:
# 금액 나누기
for i in add_BEC_index:
    com_key = int(add_BEC.loc[i, 'HS4'])
    for j in hs4_count_index:
        count = int(hs4_count.loc[j])       # count개수만큼 행 추가
        hs4Temp = int(j)
        if (count > 1) & (com_key == hs4Temp):
            for m in range(count):      # count 개수만큼 금액 나누기
                # export_2012 = (add_BEC.loc[i, 'Exported value in 2012'] / count)
                # export_2013 = (add_BEC.loc[i, 'Exported value in 2013'] / count)
                # export_2014 = (add_BEC.loc[i, 'Exported value in 2014'] / count)
                # export_2015 = (add_BEC.loc[i, 'Exported value in 2015'] / count)
                # export_2016 = (add_BEC.loc[i, 'Exported value in 2016'] / count)
                # export_2017 = (add_BEC.loc[i, 'Exported value in 2017'] / count)
                # export_2018 = (add_BEC.loc[i, 'Exported value in 2018'] / count)
                # export_2019 = (add_BEC.loc[i, 'Exported value in 2019'] / count)
                # export_2020 = (add_BEC.loc[i, 'Exported value in 2020'] / count)
                # export_2021 = (add_BEC.loc[i, 'Exported value in 2021'] / count)
                # print(export_2013)                
                # # add_BEC.loc[i, 'Exported value in 2012'] = export_2012
                # # add_BEC.loc[i, 'Exported value in 2013'] = export_2013
                # # add_BEC.loc[i, 'Exported value in 2014'] = export_2014
                # # add_BEC.loc[i, 'Exported value in 2015'] = export_2015
                # # add_BEC.loc[i, 'Exported value in 2016'] = export_2016
                # # add_BEC.loc[i, 'Exported value in 2017'] = export_2017
                # # add_BEC.loc[i, 'Exported value in 2018'] = export_2018
                # # add_BEC.loc[i, 'Exported value in 2019'] = export_2019
                # # add_BEC.loc[i, 'Exported value in 2020'] = export_2020
                # # add_BEC.loc[i, 'Exported value in 2021'] = export_2021
                add_BEC.loc[i,'Exported value in 2012']= float(add_BEC.loc[i, 'Exported value in 2012'] / count)
                add_BEC.loc[i,'Exported value in 2013']= float(add_BEC.loc[i, 'Exported value in 2013'] / count)
                add_BEC.loc[i,'Exported value in 2014']= float(add_BEC.loc[i, 'Exported value in 2014'] / count)
                add_BEC.loc[i,'Exported value in 2015']= float(add_BEC.loc[i, 'Exported value in 2015'] / count)
                add_BEC.loc[i,'Exported value in 2016']= float(add_BEC.loc[i, 'Exported value in 2016'] / count)
                add_BEC.loc[i,'Exported value in 2017']= float(add_BEC.loc[i, 'Exported value in 2017'] / count)
                add_BEC.loc[i,'Exported value in 2018']= float(add_BEC.loc[i, 'Exported value in 2018'] / count)
                add_BEC.loc[i,'Exported value in 2019']= float(add_BEC.loc[i, 'Exported value in 2019'] / count)
                add_BEC.loc[i,'Exported value in 2020']= float(add_BEC.loc[i, 'Exported value in 2020'] / count)
                add_BEC.loc[i,'Exported value in 2021']= float(add_BEC.loc[i, 'Exported value in 2021'] / count)

In [41]:
(add_BEC.loc[0, 'Exported value in 2012'] / 3)

842408.3333333334

In [ ]:
                # count_list = [
                #     (add_BEC.loc[i, 'Exported value in 2012'] / count),
                #     (add_BEC.loc[i, 'Exported value in 2013'] / count),
                #     (add_BEC.loc[i, 'Exported value in 2014'] / count),
                #     (add_BEC.loc[i, 'Exported value in 2015'] / count),
                #     (add_BEC.loc[i, 'Exported value in 2016'] / count),
                #     (add_BEC.loc[i, 'Exported value in 2017'] / count),
                #     (add_BEC.loc[i, 'Exported value in 2018'] / count),
                #     (add_BEC.loc[i, 'Exported value in 2019'] / count),
                #     (add_BEC.loc[i, 'Exported value in 2020'] / count),
                #     (add_BEC.loc[i, 'Exported value in 2021'] / count)
                # ]
                
                                # add_BEC.loc[i,'Exported value in 2012']= float(add_BEC.loc[i, 'Exported value in 2012'] / count)
                # add_BEC.loc[i,'Exported value in 2013']= float(add_BEC.loc[i, 'Exported value in 2013'] / count)
                # add_BEC.loc[i,'Exported value in 2014']= float(add_BEC.loc[i, 'Exported value in 2014'] / count)
                # add_BEC.loc[i,'Exported value in 2015']= float(add_BEC.loc[i, 'Exported value in 2015'] / count)
                # add_BEC.loc[i,'Exported value in 2016']= float(add_BEC.loc[i, 'Exported value in 2016'] / count)
                # add_BEC.loc[i,'Exported value in 2017']= float(add_BEC.loc[i, 'Exported value in 2017'] / count)
                # add_BEC.loc[i,'Exported value in 2018']= float(add_BEC.loc[i, 'Exported value in 2018'] / count)
                # add_BEC.loc[i,'Exported value in 2019']= float(add_BEC.loc[i, 'Exported value in 2019'] / count)
                # add_BEC.loc[i,'Exported value in 2020']= float(add_BEC.loc[i, 'Exported value in 2020'] / count)
                # add_BEC.loc[i,'Exported value in 2021']= float(add_BEC.loc[i, 'Exported value in 2021'] / count)

In [45]:
add_BEC

,HS,Product label,Exported value in 2012,Exported value in 2013,Exported value in 2014,Exported value in 2015,Exported value in 2016,Exported value in 2017,Exported value in 2018,Exported value in 2019,Exported value in 2020,Exported value in 2021,Unnamed: 12,HS4,BEC5Processing,BEC5Specification
0,999999,Commodities not elsewhere specified,2527225.0,5013624.0,959798.0,2293003.0,820957.0,277469.0,178658,212037,99582,88618,NaN,9999,NaN,NaN
1,291470,"Halogenated, sulphonated, nitrated or nitrosat...",64724.0,77189.0,79706.0,86934.0,74487.0,9610.0,0,0,0,0,NaN,2914,NaN,NaN
2,300210,Antisera and other blood fractions and immunol...,40082.0,57442.0,47849.0,45064.0,86696.0,17211.0,0,0,0,0,NaN,3002,NaN,NaN
3,300440,Medicaments containing alkaloids or derivative...,79025.0,44566.0,41632.0,49552.0,45286.0,2503.0,0,0,0,0,NaN,3004,NaN,NaN
4,441232,Plywood consisting solely of sheets of wood <=...,944.0,193.0,1239.0,1140.0,602.0,7.0,0,0,0,0,NaN,4412,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96,852851,Monitors of a kind solely or principally used ...,4289.0,2959.0,1779.0,1089.0,2717.0,618.0,0,0,0,0,NaN,8528,NaN,NaN
97,852851,Monitors of a kind solely or principally used ...,4289.0,2959.0,1779.0,1089.0,2717.0,618.0,0,0,0,0,NaN,8528,NaN,NaN
98,940151,Seats of bamboo or rattan,264.0,485.0,295.0,29.0,89.0,4.0,0,0,0,0,NaN,9401,NaN,NaN
99,940151,Seats of bamboo or rattan,264.0,485.0,295.0,29.0,89.0,4.0,0,0,0,0,NaN,9401,NaN,NaN
100,940151,Seats of bamboo or rattan,264.0,485.0,295.0,29.0,89.0,4.0,0,0,0,0,NaN,9401,NaN,NaN